site_name: jameswillett.dev
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
  - glightbox
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - tags
  - privacy

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: simple/youtube
      link: https://youtube.com/@james-willett
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2024 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>

nav:
  - index.md
  - Business Method:
    - businessMethod/index.md
    - Product Ideas:
      - Stage 1 - Initial Brainstorming: businessMethod/productIdeas/initial-brainstorming.md
      - Stage 2 - Possible Solutions: businessMethod/productIdeas/possible-solutions.md
      - Stage 3 - Market Research: businessMethod/productIdeas/market-research.md
      - Stage 4 - Test Ideas: businessMethod/productIdeas/testing-ideas.md
    - Competitors and Inspiration: businessMethod/competitors.md
    - User Personas:
      - Demographics:
        - Age Groups and Geo Locations: businessMethod/buyerPersonas/demographics/age-groups.md
        - Niche Markets: businessMethod/buyerPersonas/demographics/niche-markets.md
        - Interests and Hobbies: businessMethod/buyerPersonas/demographics/interests-hobbies.md
        - Educational Backgrounds: businessMethod/buyerPersonas/demographics/educational-background.md
        - Jobs and Professions: businessMethod/buyerPersonas/demographics/professions.md
        - Income Levels: businessMethod/buyerPersonas/demographics/income.md
      - Customer Preferences:
        - Pain Points: businessMethod/buyerPersonas/customerPreferences/pain-points.md
        - Purchase Frequency: businessMethod/buyerPersonas/customerPreferences/purchase-frequency.md
        - Brand Loyalty: businessMethod/buyerPersonas/customerPreferences/brand-loyalty.md
        - Brand Loyalty Specifics: businessMethod/buyerPersonas/customerPreferences/brand-loyalty-specifics.md
        - Decision Making: businessMethod/buyerPersonas/customerPreferences/decision-making.md
        - Values and Attitudes: businessMethod/buyerPersonas/customerPreferences/values-attitudes.md
        - Psychological Factors: businessMethod/buyerPersonas/customerPreferences/psychological-factors.md
      - Customer Communication:
        - Needs and Desires: businessMethod/buyerPersonas/customerCommunication/needs-desires.md
        - Communication Channels: businessMethod/buyerPersonas/customerCommunication/communication-channels.md
        - Reaching my Audience: businessMethod/buyerPersonas/customerCommunication/reaching-audience.md
        - Customer Buying Decisions: businessMethod/buyerPersonas/customerCommunication/research-methods.md
        - Key Influencers: businessMethod/buyerPersonas/customerCommunication/key-influencers.md
        - Value Propositions: businessMethod/buyerPersonas/customerCommunication/value-propositions.md
        - Communication Tone: businessMethod/buyerPersonas/customerCommunication/communication-tone.md
        - Features and Benefits: businessMethod/buyerPersonas/customerCommunication/features-benefits.md
        - Marketing Strategy: businessMethod/buyerPersonas/customerCommunication/marketing-strategy.md
        - Campaigns and Promotions: businessMethod/buyerPersonas/customerCommunication/campaigns-promotions.md
        - Example Marketing Campaigns: businessMethod/buyerPersonas/customerCommunication/example-campaigns.md
        - Marketing Metrics: businessMethod/buyerPersonas/customerCommunication/marketing-metrics.md
      - Final User Personas:
        - Emily - Early Career Engineer: businessMethod/buyerPersonas/userPersonas/1-early-career-engineer.md
        - Mark - Personal Brand Builder: businessMethod/buyerPersonas/userPersonas/2-brand-builder.md
        - Penni - Content Monetiser: businessMethod/buyerPersonas/userPersonas/3-content-monetiser.md
    - Mission Statement: businessMethod/mission-statement.md
